export declare enum ErrorCode {
    INVALID_CERTIFICATE_CHAIN = 100,
    INVALID_TOKEN_SIGNATURE = 101,
    INVALID_CLIENT_DOMAIN = 102,
    EXPIRED_ACCESS_TOKEN = 103,
    DISABLED_ACCESS_TOKEN = 104,
    DECRYPT_PAYLOAD_ERROR = 105,
    INVALID_ACCESS_TOKEN_TYPE = 106,
    ACCESS_TOKEN_ID_EMPTY = 107
}
